spring.application.name=twitterapi

server.port=${SERVER_PORT}
server.servlet.context-path=${CONTEXT_PATH}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Logging Levels ->

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE